# Site settings
title: Can They See My Dick?
description: Can the US government see your dick pics?
call_to_action: >
  Help the Electronic Frontier Foundation fight to keep your dick pics private
  and <a href="https://act.eff.org/action/tell-congress-my-phone-calls-are-my-business-reform-the-nsa">tell the United States Congress to limit the Patriot Act</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cantheyseemydick.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
